[package]
authors = ["Rikard Anglerud <rikard@anglerud.com>"]
name = "hootie"
version = "0.5.0"
description = """
Terminal viewer of Alerta alerts.
"""
homepage = "https://github.com/anglerud/hootie"
repository = "https://github.com/anglerud/hootie"
readme = "README.md"
keywords = ["alerta", "alerting"]
categories = ["command-line-interface"]
license = "GPL-3.0"
maintenance = { status = "actively-developed" }
exclude = [
    "fake_alerta/*"
]

[dependencies]
failure = "0.1.1"
reqwest = "0.8.2"
serde = "1.0.26"
serde_derive = "1.0.26"
structopt = "0.1.0"
structopt-derive = "0.1.0"
termion = "1.5.1"
